// Comprehensive pet and animal database with images
const animalsData = [
  // Dogs
  {
    id: 1,
    name: "Golden Retriever",
    type: "dog",
    size: "large",
    activity: "high",
    care: "moderate",
    lifespan: "10-12 years",
    weight: "55-75 lbs",
    origin: "Scotland",
    description:
      "Friendly, intelligent, and devoted. Golden Retrievers are among America's most popular dog breeds. They're serious workers at hunting and field work, as guides for the blind, and in search-and-rescue.",
    image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400",
  },
  {
    id: 2,
    name: "French Bulldog",
    type: "dog",
    size: "small",
    activity: "low",
    care: "easy",
    lifespan: "10-12 years",
    weight: "20-28 lbs",
    origin: "France",
    description:
      "The French Bulldog is a breed of domestic dog. They are the result of a cross between Toy Bulldogs imported from England and local ratters in Paris in the 1800s.",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400",
  },
  {
    id: 3,
    name: "German Shepherd",
    type: "dog",
    size: "large",
    activity: "high",
    care: "moderate",
    lifespan: "9-13 years",
    weight: "50-90 lbs",
    origin: "Germany",
    description:
      "Large-sized working dog that originated in Germany. They are extremely versatile, serving as family companions, guard dogs, and in many other capacities.",
    image: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400",
  },
  {
    id: 4,
    name: "Labrador Retriever",
    type: "dog",
    size: "large",
    activity: "high",
    care: "easy",
    lifespan: "10-12 years",
    weight: "55-80 lbs",
    origin: "Canada",
    description:
      "America's most popular dog breed. Labs are friendly, outgoing, and active companions who have more than enough affection to go around for a family looking for a medium to large dog.",
    image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400",
  },
  {
    id: 5,
    name: "Poodle",
    type: "dog",
    size: "medium",
    activity: "moderate",
    care: "difficult",
    lifespan: "12-15 years",
    weight: "45-70 lbs",
    origin: "Germany/France",
    description:
      "Exceptional intelligence and trainability. Poodles come in three sizes and many colors. They're athletic and graceful with a hypoallergenic coat.",
    image: "https://images.unsplash.com/photo-1616190909291-6fbb88671f03?w=400",
  },
  {
    id: 6,
    name: "Chihuahua",
    type: "dog",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "14-16 years",
    weight: "2-6 lbs",
    origin: "Mexico",
    description:
      "A tiny dog with a huge personality. Chihuahuas are excellent watchdogs and loyal companions. They're perfect for apartment living.",
    image: "https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=400",
  },

  // Cats
  {
    id: 7,
    name: "Persian Cat",
    type: "cat",
    size: "medium",
    activity: "low",
    care: "difficult",
    lifespan: "12-17 years",
    weight: "7-12 lbs",
    origin: "Iran",
    description:
      "Known for their long, luxurious coat and sweet personalities. Persian cats are quiet, gentle, and prefer a serene environment.",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400",
  },
  {
    id: 8,
    name: "Maine Coon",
    type: "cat",
    size: "large",
    activity: "moderate",
    care: "moderate",
    lifespan: "13-14 years",
    weight: "10-25 lbs",
    origin: "United States",
    description:
      "One of the largest domesticated cat breeds. Known for their intelligence, playful personality, and distinctive physical appearance.",
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400",
  },
  {
    id: 9,
    name: "Siamese Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "easy",
    lifespan: "12-15 years",
    weight: "6-14 lbs",
    origin: "Thailand",
    description:
      "Known for their distinctive color pattern, blue eyes, and vocal nature. Siamese cats are intelligent, social, and very active.",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400",
  },

  // Birds
  {
    id: 10,
    name: "Budgerigar",
    type: "bird",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "5-10 years",
    weight: "1-1.4 oz",
    origin: "Australia",
    description:
      "Small, long-tailed, seed-eating parrots. Budgies are playful, intelligent, and can learn to mimic human speech.",
    image: "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=400",
  },
  {
    id: 11,
    name: "Canary",
    type: "bird",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "10-15 years",
    weight: "0.5-1 oz",
    origin: "Canary Islands",
    description:
      "Small songbirds known for their beautiful singing ability. They're relatively easy to care for and make delightful companions.",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
  },
  {
    id: 12,
    name: "Cockatiel",
    type: "bird",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "15-25 years",
    weight: "2.5-3.5 oz",
    origin: "Australia",
    description:
      "Known for their distinctive crest and orange cheek patches. Cockatiels are social, intelligent, and can learn simple tunes.",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=400",
  },

  // Fish
  {
    id: 13,
    name: "Goldfish",
    type: "fish",
    size: "small",
    activity: "low",
    care: "easy",
    lifespan: "10-30 years",
    weight: "0.2-0.6 lbs",
    origin: "China",
    description:
      "One of the most popular aquarium fish. Goldfish are hardy, peaceful, and can live for many years with proper care.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
  },
  {
    id: 14,
    name: "Betta Fish",
    type: "fish",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "2-4 years",
    weight: "0.1 oz",
    origin: "Thailand",
    description:
      "Also known as Siamese fighting fish. Known for their vibrant colors and flowing fins. Males are territorial and should be kept alone.",
    image: "https://images.unsplash.com/photo-1520637836862-4d197d17c50a?w=400",
  },
  {
    id: 15,
    name: "Clownfish",
    type: "fish",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "6-10 years",
    weight: "0.5-1 oz",
    origin: "Indo-Pacific",
    description:
      "Colorful marine fish known for their symbiotic relationship with sea anemones. Popular in saltwater aquariums.",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
  },

  // Reptiles
  {
    id: 16,
    name: "Bearded Dragon",
    type: "reptile",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "1-2 lbs",
    origin: "Australia",
    description:
      "Docile lizards that make excellent pets. They're known for their calm temperament and distinctive 'beard' display.",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
  },
  {
    id: 17,
    name: "Leopard Gecko",
    type: "reptile",
    size: "small",
    activity: "low",
    care: "easy",
    lifespan: "15-20 years",
    weight: "2-3 oz",
    origin: "Afghanistan/Pakistan",
    description:
      "Small, spotted geckos that are nocturnal and easy to care for. They don't require UV lighting like many other reptiles.",
    image: "https://images.unsplash.com/photo-1607163912046-e1bbbc44fb9c?w=400",
  },

  // Rabbits
  {
    id: 18,
    name: "Holland Lop",
    type: "rabbit",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "7-12 years",
    weight: "2-4 lbs",
    origin: "Netherlands",
    description:
      "Small rabbits with distinctive drooping ears. They're gentle, friendly, and make excellent indoor pets.",
    image: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400",
  },
  {
    id: 19,
    name: "Flemish Giant",
    type: "rabbit",
    size: "large",
    activity: "low",
    care: "moderate",
    lifespan: "8-10 years",
    weight: "14-20 lbs",
    origin: "Belgium",
    description:
      "One of the largest rabbit breeds. Despite their size, they're known for being gentle giants with calm temperaments.",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
  },

  // Hamsters
  {
    id: 20,
    name: "Syrian Hamster",
    type: "hamster",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "2-3 years",
    weight: "3-5 oz",
    origin: "Syria",
    description:
      "Also known as golden hamsters. They're solitary animals and should be housed alone. They're nocturnal and very active.",
    image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400",
  },

  // Exotic Pets
  {
    id: 21,
    name: "Chinchilla",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "10-20 years",
    weight: "1-2 lbs",
    origin: "South America",
    description:
      "Known for their incredibly soft fur. They require special care including dust baths and cool temperatures.",
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=400",
  },
  {
    id: 22,
    name: "Ferret",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "7-10 years",
    weight: "1-2.5 lbs",
    origin: "Europe",
    description:
      "Playful, curious animals that require significant attention and exercise. They're social and do best in pairs or groups.",
    image: "https://images.unsplash.com/photo-1593003485648-3b5c1b8e1efd?w=400",
  },
  {
    id: 23,
    name: "Sugar Glider",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "10-15 years",
    weight: "3-5 oz",
    origin: "Australia",
    description:
      "Small marsupials that can glide between trees. They're social, nocturnal, and require specialized diets and care.",
    image: "https://images.unsplash.com/photo-1606916247511-baa5ee1020b1?w=400",
  },
  {
    id: 24,
    name: "Axolotl",
    type: "exotic",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "2-8 oz",
    origin: "Mexico",
    description:
      "Aquatic salamanders that remain in their larval form throughout life. They're unique pets that require cool, clean water.",
    image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
  },
  {
    id: 25,
    name: "Hedgehog",
    type: "exotic",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "3-8 years",
    weight: "0.5-1.5 lbs",
    origin: "Africa",
    description:
      "Small, spiny mammals that are nocturnal and can be quite social with proper handling. They require warm environments.",
    image: "https://images.unsplash.com/photo-1574418747767-43f36d259edb?w=400",
  },

  // More Dogs
  {
    id: 26,
    name: "Border Collie",
    type: "dog",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "12-15 years",
    weight: "30-55 lbs",
    origin: "Scotland",
    description:
      "Extremely intelligent and energetic herding dogs. They require mental stimulation and physical exercise to prevent destructive behavior.",
    image: "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400",
  },
  {
    id: 27,
    name: "Shiba Inu",
    type: "dog",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "13-16 years",
    weight: "17-23 lbs",
    origin: "Japan",
    description:
      "Independent, alert dogs with a fox-like appearance. They're clean, quiet, and have a strong-willed personality.",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400",
  },
  {
    id: 28,
    name: "Dalmatian",
    type: "dog",
    size: "large",
    activity: "high",
    care: "moderate",
    lifespan: "11-13 years",
    weight: "45-70 lbs",
    origin: "Croatia",
    description:
      "Distinctive spotted dogs known for their endurance and energy. They require regular exercise and early socialization.",
    image: "https://images.unsplash.com/photo-1605460375648-278bcbd579a6?w=400",
  },

  // More Cats
  {
    id: 29,
    name: "Bengal Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "moderate",
    lifespan: "12-16 years",
    weight: "8-15 lbs",
    origin: "United States",
    description:
      "Wild-looking cats with leopard-like spots. They're active, playful, and intelligent, often enjoying water and climbing.",
    image: "https://images.unsplash.com/photo-1574231164645-d6f0e8553590?w=400",
  },
  {
    id: 30,
    name: "Ragdoll Cat",
    type: "cat",
    size: "large",
    activity: "low",
    care: "moderate",
    lifespan: "12-17 years",
    weight: "10-20 lbs",
    origin: "United States",
    description:
      "Known for their docile temperament and tendency to go limp when picked up. They're affectionate, gentle, and great with children.",
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400",
  },
  {
    id: 31,
    name: "Russian Blue",
    type: "cat",
    size: "medium",
    activity: "moderate",
    care: "easy",
    lifespan: "15-20 years",
    weight: "7-12 lbs",
    origin: "Russia",
    description:
      "Known for their silvery-blue coat and green eyes. They're intelligent, loyal, and somewhat reserved with strangers.",
    image: "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?w=400",
  },

  // More Birds
  {
    id: 32,
    name: "African Grey Parrot",
    type: "bird",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "40-60 years",
    weight: "14-18 oz",
    origin: "Africa",
    description:
      "Highly intelligent parrots known for their ability to mimic human speech and solve problems. They require significant mental stimulation.",
    image: "https://images.unsplash.com/photo-1580473354932-ad14ad2dca90?w=400",
  },
  {
    id: 33,
    name: "Lovebird",
    type: "bird",
    size: "small",
    activity: "high",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "1.5-2.5 oz",
    origin: "Africa",
    description:
      "Small, colorful parrots known for their affectionate nature with their mates. They're social and do best in pairs.",
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400",
  },

  // More Fish
  {
    id: 34,
    name: "Angelfish",
    type: "fish",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "10-12 years",
    weight: "0.5-1 oz",
    origin: "South America",
    description:
      "Graceful freshwater fish with distinctive triangular shape. They're peaceful community fish when properly cared for.",
    image: "https://images.unsplash.com/photo-1560114928-40f1f1eb26a0?w=400",
  },
  {
    id: 35,
    name: "Neon Tetra",
    type: "fish",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "5-10 years",
    weight: "0.1 oz",
    origin: "South America",
    description:
      "Small, colorful schooling fish with bright blue and red stripes. They're peaceful and perfect for community aquariums.",
    image: "https://images.unsplash.com/photo-1544551763-77043f0c95b7?w=400",
  },

  // More Reptiles
  {
    id: 36,
    name: "Ball Python",
    type: "reptile",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "20-30 years",
    weight: "3-5 lbs",
    origin: "Africa",
    description:
      "Non-venomous snakes known for curling into a ball when threatened. They're docile and make good pets for experienced handlers.",
    image: "https://images.unsplash.com/photo-1531386151447-fd76e2e1ead5?w=400",
  },
  {
    id: 37,
    name: "Corn Snake",
    type: "reptile",
    size: "medium",
    activity: "low",
    care: "easy",
    lifespan: "15-20 years",
    weight: "1-2 lbs",
    origin: "United States",
    description:
      "Docile, easy-to-care-for snakes that come in many color varieties. They're perfect for beginners to snake keeping.",
    image: "https://images.unsplash.com/photo-1593015542923-2ff55e8b9dd6?w=400",
  },

  // More Exotic Animals
  {
    id: 38,
    name: "Guinea Pig",
    type: "exotic",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "4-8 years",
    weight: "1.5-2.5 lbs",
    origin: "South America",
    description:
      "Social, vocal animals that make excellent pets for families. They require vitamin C in their diet and do best in pairs or groups.",
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=400",
  },
  {
    id: 39,
    name: "Cockatiel",
    type: "bird",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "15-25 years",
    weight: "2.5-3.5 oz",
    origin: "Australia",
    description:
      "Known for their distinctive crest and orange cheek patches. Cockatiels are social, intelligent, and can learn simple tunes.",
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=400",
  },
  {
    id: 40,
    name: "Dwarf Hamster",
    type: "hamster",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "1.5-3 years",
    weight: "1-2 oz",
    origin: "Mongolia/Siberia",
    description:
      "Smaller than Syrian hamsters and can sometimes be kept in pairs. They're very active and entertaining to watch.",
    image: "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=400",
  },

  // Marine Animals
  {
    id: 41,
    name: "Seahorse",
    type: "fish",
    size: "small",
    activity: "low",
    care: "difficult",
    lifespan: "1-5 years",
    weight: "0.1-1 oz",
    origin: "Worldwide Oceans",
    description:
      "Unique marine fish with horse-like heads. They require specialized care with live or frozen foods and gentle water movement.",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
  },
  {
    id: 42,
    name: "Octopus",
    type: "exotic",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "1-2 years",
    weight: "2-10 lbs",
    origin: "Worldwide Oceans",
    description:
      "Highly intelligent marine invertebrates. They require expert-level care with escape-proof tanks and specialized feeding.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
  },

  // Amphibians
  {
    id: 43,
    name: "Fire Salamander",
    type: "reptile",
    size: "small",
    activity: "low",
    care: "moderate",
    lifespan: "10-50 years",
    weight: "1-2 oz",
    origin: "Europe",
    description:
      "Striking black salamanders with yellow spots. They're terrestrial amphibians that require humid environments and careful temperature control.",
    image: "https://images.unsplash.com/photo-1606916247511-baa5ee1020b1?w=400",
  },
  {
    id: 44,
    name: "Poison Dart Frog",
    type: "reptile",
    size: "small",
    activity: "moderate",
    care: "difficult",
    lifespan: "5-7 years",
    weight: "0.1-0.3 oz",
    origin: "Central/South America",
    description:
      "Brightly colored frogs that require specialized terrarium setups. Captive-bred specimens are not toxic and make fascinating pets.",
    image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
  },

  // Large Animals
  {
    id: 45,
    name: "Miniature Horse",
    type: "exotic",
    size: "large",
    activity: "moderate",
    care: "difficult",
    lifespan: "25-35 years",
    weight: "150-350 lbs",
    origin: "Europe",
    description:
      "Small horses that stand under 34 inches tall. They require pasture space, specialized care, and can make wonderful companions.",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=400",
  },

  {
    id: 50,
    name: "Green Iguana",
    type: "reptile",
    size: "large",
    activity: "moderate",
    care: "difficult",
    lifespan: "15-20 years",
    weight: "4-17 lbs",
    origin: "Central/South America",
    description:
      "Large herbivorous lizards that require extensive care, large enclosures, and proper UV lighting. They can grow quite large and live many years.",
  },

  // More Exotic Pets
  {
    id: 51,
    name: "Guinea Pig",
    type: "exotic",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "4-8 years",
    weight: "1.5-2.5 lbs",
    origin: "South America",
    description:
      "Social, vocal animals that make excellent pets for families. They require vitamin C in their diet and do best in pairs or groups.",
  },
  {
    id: 52,
    name: "Prairie Dog",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "8-10 years",
    weight: "2-4 lbs",
    origin: "North America",
    description:
      "Highly social rodents that live in complex burrow systems. They require specialized care and are illegal to own in some areas.",
  },
  {
    id: 53,
    name: "Capybara",
    type: "exotic",
    size: "large",
    activity: "moderate",
    care: "difficult",
    lifespan: "8-10 years",
    weight: "77-146 lbs",
    origin: "South America",
    description:
      "The world's largest rodent. They're semi-aquatic and highly social animals that require access to water and companionship.",
  },
  {
    id: 54,
    name: "Fennec Fox",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "10-14 years",
    weight: "2-3.5 lbs",
    origin: "North Africa",
    description:
      "Small desert foxes with large ears. They're nocturnal, energetic, and require specialized care. Legal restrictions vary by location.",
  },

  // More Dogs
  {
    id: 55,
    name: "Australian Cattle Dog",
    type: "dog",
    size: "medium",
    activity: "high",
    care: "moderate",
    lifespan: "12-16 years",
    weight: "31-35 lbs",
    origin: "Australia",
    description:
      "Extremely active working dogs bred for herding cattle. They require intensive exercise and mental stimulation.",
  },
  {
    id: 56,
    name: "Shiba Inu",
    type: "dog",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "13-16 years",
    weight: "17-23 lbs",
    origin: "Japan",
    description:
      "Independent, alert dogs with a fox-like appearance. They're clean, quiet, and have a strong-willed personality.",
  },
  {
    id: 57,
    name: "Basset Hound",
    type: "dog",
    size: "medium",
    activity: "low",
    care: "easy",
    lifespan: "12-13 years",
    weight: "40-65 lbs",
    origin: "France",
    description:
      "Short-legged hounds with excellent scenting ability. They're gentle, patient, and great with children.",
  },
  {
    id: 58,
    name: "Dalmatian",
    type: "dog",
    size: "large",
    activity: "high",
    care: "moderate",
    lifespan: "11-13 years",
    weight: "45-70 lbs",
    origin: "Croatia",
    description:
      "Distinctive spotted dogs known for their endurance and energy. They require regular exercise and early socialization.",
  },

  // More Cats
  {
    id: 59,
    name: "Abyssinian Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "easy",
    lifespan: "9-15 years",
    weight: "6-10 lbs",
    origin: "Egypt/Ethiopia",
    description:
      "Active, playful cats with ticked coats. They're intelligent, curious, and enjoy climbing and exploring.",
  },
  {
    id: 60,
    name: "Norwegian Forest Cat",
    type: "cat",
    size: "large",
    activity: "moderate",
    care: "moderate",
    lifespan: "14-16 years",
    weight: "12-16 lbs",
    origin: "Norway",
    description:
      "Large, fluffy cats adapted to cold climates. They're gentle, patient, and excellent climbers with water-resistant coats.",
  },
  {
    id: 61,
    name: "Sphynx Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "8-14 years",
    weight: "6-12 lbs",
    origin: "Canada",
    description:
      "Hairless cats known for their warm skin and extroverted personalities. They require special skin care and protection from sun and cold.",
  },

  // More Birds
  {
    id: 62,
    name: "Conure",
    type: "bird",
    size: "small",
    activity: "high",
    care: "moderate",
    lifespan: "20-30 years",
    weight: "3-5 oz",
    origin: "South America",
    description:
      "Colorful, playful parrots known for their loud calls and acrobatic abilities. They're social and bond strongly with their owners.",
  },
  {
    id: 63,
    name: "Finch",
    type: "bird",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "5-10 years",
    weight: "0.3-0.8 oz",
    origin: "Worldwide",
    description:
      "Small, social songbirds that do best in flocks. They're active, colorful, and relatively easy to care for in aviaries.",
  },
  {
    id: 64,
    name: "Quaker Parrot",
    type: "bird",
    size: "small",
    activity: "high",
    care: "moderate",
    lifespan: "20-30 years",
    weight: "3-5 oz",
    origin: "South America",
    description:
      "Intelligent, talkative parrots that build large communal nests. They're social, playful, and can learn extensive vocabularies.",
  },

  // More Fish
  {
    id: 65,
    name: "Oscar Fish",
    type: "fish",
    size: "large",
    activity: "moderate",
    care: "moderate",
    lifespan: "10-20 years",
    weight: "2-3.5 lbs",
    origin: "South America",
    description:
      "Large, intelligent cichlids that can recognize their owners. They're messy eaters and require large aquariums with strong filtration.",
  },
  {
    id: 66,
    name: "Koi Fish",
    type: "fish",
    size: "large",
    activity: "moderate",
    care: "moderate",
    lifespan: "25-35 years",
    weight: "4-35 lbs",
    origin: "Japan",
    description:
      "Ornamental carp bred for their beautiful colors and patterns. They're typically kept in outdoor ponds and can live for decades.",
  },
  {
    id: 67,
    name: "Molly Fish",
    type: "fish",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "3-5 years",
    weight: "0.3-0.5 oz",
    origin: "Mexico",
    description:
      "Hardy freshwater fish that come in many colors. They're peaceful community fish and easy to breed.",
  },

  // Amphibians
  {
    id: 68,
    name: "White's Tree Frog",
    type: "reptile",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "7-21 years",
    weight: "2-4 oz",
    origin: "Australia",
    description:
      "Large, docile tree frogs that are excellent for beginners. They're known for their calm temperament and distinctive appearance.",
  },
  {
    id: 69,
    name: "Fire Salamander",
    type: "reptile",
    size: "small",
    activity: "low",
    care: "moderate",
    lifespan: "10-50 years",
    weight: "1-2 oz",
    origin: "Europe",
    description:
      "Striking black salamanders with yellow spots. They're terrestrial amphibians that require humid environments and careful temperature control.",
  },
  {
    id: 70,
    name: "Crested Gecko",
    type: "reptile",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "15-20 years",
    weight: "1-2 oz",
    origin: "New Caledonia",
    description:
      "Arboreal geckos with distinctive crests and the ability to climb glass. They're easy to care for and don't require UV lighting.",
  },
  {
    id: 71,
    name: "German Shepherd",
    type: "dog",
    size: "large",
    activity: "high",
    care: "moderate",
    lifespan: "9-13 years",
    weight: "50-90 lbs",
    origin: "Germany",
    description:
      "Large-sized working dog that originated in Germany. They are extremely versatile, serving as family companions, guard dogs, and in many other capacities.",
  },
  {
    id: 72,
    name: "Labrador Retriever",
    type: "dog",
    size: "large",
    activity: "high",
    care: "easy",
    lifespan: "10-12 years",
    weight: "55-80 lbs",
    origin: "Canada",
    description:
      "America's most popular dog breed. Labs are friendly, outgoing, and active companions who have more than enough affection to go around for a family looking for a medium to large dog.",
  },
  {
    id: 73,
    name: "Poodle",
    type: "dog",
    size: "medium",
    activity: "moderate",
    care: "difficult",
    lifespan: "12-15 years",
    weight: "45-70 lbs",
    origin: "Germany/France",
    description:
      "Exceptional intelligence and trainability. Poodles come in three sizes and many colors. They're athletic and graceful with a hypoallergenic coat.",
  },
  {
    id: 74,
    name: "Chihuahua",
    type: "dog",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "14-16 years",
    weight: "2-6 lbs",
    origin: "Mexico",
    description:
      "A tiny dog with a huge personality. Chihuahuas are excellent watchdogs and loyal companions. They're perfect for apartment living.",
  },

  // Cats
  {
    id: 75,
    name: "Persian Cat",
    type: "cat",
    size: "medium",
    activity: "low",
    care: "difficult",
    lifespan: "12-17 years",
    weight: "7-12 lbs",
    origin: "Iran",
    description:
      "Known for their long, luxurious coat and sweet personalities. Persian cats are quiet, gentle, and prefer a serene environment.",
  },
  {
    id: 76,
    name: "Maine Coon",
    type: "cat",
    size: "large",
    activity: "moderate",
    care: "moderate",
    lifespan: "13-14 years",
    weight: "10-25 lbs",
    origin: "United States",
    description:
      "One of the largest domesticated cat breeds. Known for their intelligence, playful personality, and distinctive physical appearance.",
  },
  {
    id: 77,
    name: "Siamese Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "easy",
    lifespan: "12-15 years",
    weight: "6-14 lbs",
    origin: "Thailand",
    description:
      "Known for their distinctive color pattern, blue eyes, and vocal nature. Siamese cats are intelligent, social, and very active.",
  },
  {
    id: 78,
    name: "British Shorthair",
    type: "cat",
    size: "medium",
    activity: "low",
    care: "easy",
    lifespan: "12-17 years",
    weight: "9-17 lbs",
    origin: "United Kingdom",
    description:
      "Known for their chunky appearance and dense coat. They're calm, good-natured, and make excellent companions.",
  },
  {
    id: 79,
    name: "Ragdoll Cat",
    type: "cat",
    size: "large",
    activity: "low",
    care: "moderate",
    lifespan: "12-17 years",
    weight: "10-20 lbs",
    origin: "United States",
    description:
      "Known for their docile temperament and tendency to go limp when picked up. They're affectionate, gentle, and great with children.",
  },

  // Birds
  {
    id: 80,
    name: "Budgerigar",
    type: "bird",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "5-10 years",
    weight: "1-1.4 oz",
    origin: "Australia",
    description:
      "Small, long-tailed, seed-eating parrots. Budgies are playful, intelligent, and can learn to mimic human speech.",
  },
  {
    id: 81,
    name: "Canary",
    type: "bird",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "10-15 years",
    weight: "0.5-1 oz",
    origin: "Canary Islands",
    description:
      "Small songbirds known for their beautiful singing ability. They're relatively easy to care for and make delightful companions.",
  },
  {
    id: 82,
    name: "Cockatiel",
    type: "bird",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "15-25 years",
    weight: "2.5-3.5 oz",
    origin: "Australia",
    description:
      "Known for their distinctive crest and orange cheek patches. Cockatiels are social, intelligent, and can learn simple tunes.",
  },
  {
    id: 83,
    name: "African Grey Parrot",
    type: "bird",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "40-60 years",
    weight: "14-18 oz",
    origin: "Africa",
    description:
      "Highly intelligent parrots known for their ability to mimic human speech and solve problems. They require significant mental stimulation.",
  },
  {
    id: 84,
    name: "Macaw",
    type: "bird",
    size: "large",
    activity: "high",
    care: "difficult",
    lifespan: "50-100 years",
    weight: "2-4 lbs",
    origin: "South America",
    description:
      "Large, colorful parrots with powerful beaks. They're intelligent, social, and require extensive care and attention.",
  },

  // Fish
  {
    id: 85,
    name: "Goldfish",
    type: "fish",
    size: "small",
    activity: "low",
    care: "easy",
    lifespan: "10-30 years",
    weight: "0.2-0.6 lbs",
    origin: "China",
    description:
      "One of the most popular aquarium fish. Goldfish are hardy, peaceful, and can live for many years with proper care.",
  },
  {
    id: 86,
    name: "Betta Fish",
    type: "fish",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "2-4 years",
    weight: "0.1 oz",
    origin: "Thailand",
    description:
      "Also known as Siamese fighting fish. Known for their vibrant colors and flowing fins. Males are territorial and should be kept alone.",
  },
  {
    id: 87,
    name: "Angelfish",
    type: "fish",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "10-12 years",
    weight: "0.5-1 oz",
    origin: "South America",
    description:
      "Graceful freshwater fish with distinctive triangular shape. They're peaceful community fish when properly cared for.",
  },
  {
    id: 88,
    name: "Clownfish",
    type: "fish",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "6-10 years",
    weight: "0.5-1 oz",
    origin: "Indo-Pacific",
    description:
      "Colorful marine fish known for their symbiotic relationship with sea anemones. Popular in saltwater aquariums.",
  },
  {
    id: 89,
    name: "Guppy",
    type: "fish",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "1-3 years",
    weight: "0.1 oz",
    origin: "South America",
    description:
      "Small, colorful freshwater fish that are easy to breed and care for. They're active swimmers and come in many color varieties.",
  },

  // Reptiles
  {
    id: 90,
    name: "Bearded Dragon",
    type: "reptile",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "1-2 lbs",
    origin: "Australia",
    description:
      "Docile lizards that make excellent pets. They're known for their calm temperament and distinctive 'beard' display.",
  },
  {
    id: 91,
    name: "Leopard Gecko",
    type: "reptile",
    size: "small",
    activity: "low",
    care: "easy",
    lifespan: "15-20 years",
    weight: "2-3 oz",
    origin: "Afghanistan/Pakistan",
    description:
      "Small, spotted geckos that are nocturnal and easy to care for. They don't require UV lighting like many other reptiles.",
  },
  {
    id: 24,
    name: "Ball Python",
    type: "reptile",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "20-30 years",
    weight: "3-5 lbs",
    origin: "Africa",
    description:
      "Non-venomous snakes known for curling into a ball when threatened. They're docile and make good pets for experienced handlers.",
  },
  {
    id: 25,
    name: "Red-Eared Slider",
    type: "reptile",
    size: "medium",
    activity: "moderate",
    care: "moderate",
    lifespan: "20-40 years",
    weight: "1-3 lbs",
    origin: "Southern United States",
    description:
      "Semi-aquatic turtles with distinctive red markings behind their eyes. They require both water and basking areas.",
  },

  // Rabbits
  {
    id: 26,
    name: "Holland Lop",
    type: "rabbit",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "7-12 years",
    weight: "2-4 lbs",
    origin: "Netherlands",
    description:
      "Small rabbits with distinctive drooping ears. They're gentle, friendly, and make excellent indoor pets.",
  },
  {
    id: 27,
    name: "Flemish Giant",
    type: "rabbit",
    size: "large",
    activity: "low",
    care: "moderate",
    lifespan: "8-10 years",
    weight: "14-20 lbs",
    origin: "Belgium",
    description:
      "One of the largest rabbit breeds. Despite their size, they're known for being gentle giants with calm temperaments.",
  },
  {
    id: 28,
    name: "Lionhead Rabbit",
    type: "rabbit",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "7-10 years",
    weight: "2.5-3.5 lbs",
    origin: "Belgium",
    description:
      "Known for their distinctive mane of long fur around their head. They're energetic and require regular grooming.",
  },
  {
    id: 29,
    name: "Mini Rex",
    type: "rabbit",
    size: "small",
    activity: "moderate",
    care: "easy",
    lifespan: "5-7 years",
    weight: "3-4.5 lbs",
    origin: "United States",
    description:
      "Known for their incredibly soft, velvety fur. They're calm, friendly, and make excellent pets for families.",
  },

  // Hamsters
  {
    id: 30,
    name: "Syrian Hamster",
    type: "hamster",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "2-3 years",
    weight: "3-5 oz",
    origin: "Syria",
    description:
      "Also known as golden hamsters. They're solitary animals and should be housed alone. They're nocturnal and very active.",
  },
  {
    id: 31,
    name: "Dwarf Hamster",
    type: "hamster",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "1.5-3 years",
    weight: "1-2 oz",
    origin: "Mongolia/Siberia",
    description:
      "Smaller than Syrian hamsters and can sometimes be kept in pairs. They're very active and entertaining to watch.",
  },
  {
    id: 32,
    name: "Roborovski Hamster",
    type: "hamster",
    size: "small",
    activity: "high",
    care: "moderate",
    lifespan: "2-4 years",
    weight: "0.5-1 oz",
    origin: "Mongolia/China",
    description:
      "The smallest and fastest hamster species. They're social with their own kind and very active, especially at night.",
  },

  // Exotic Pets
  {
    id: 33,
    name: "Chinchilla",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "10-20 years",
    weight: "1-2 lbs",
    origin: "South America",
    description:
      "Known for their incredibly soft fur. They require special care including dust baths and cool temperatures.",
  },
  {
    id: 34,
    name: "Ferret",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "7-10 years",
    weight: "1-2.5 lbs",
    origin: "Europe",
    description:
      "Playful, curious animals that require significant attention and exercise. They're social and do best in pairs or groups.",
  },
  {
    id: 35,
    name: "Sugar Glider",
    type: "exotic",
    size: "small",
    activity: "high",
    care: "difficult",
    lifespan: "10-15 years",
    weight: "3-5 oz",
    origin: "Australia",
    description:
      "Small marsupials that can glide between trees. They're social, nocturnal, and require specialized diets and care.",
  },
  {
    id: 36,
    name: "Axolotl",
    type: "exotic",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "2-8 oz",
    origin: "Mexico",
    description:
      "Aquatic salamanders that remain in their larval form throughout life. They're unique pets that require cool, clean water.",
  },
  {
    id: 37,
    name: "Hedgehog",
    type: "exotic",
    size: "small",
    activity: "moderate",
    care: "moderate",
    lifespan: "3-8 years",
    weight: "0.5-1.5 lbs",
    origin: "Africa",
    description:
      "Small, spiny mammals that are nocturnal and can be quite social with proper handling. They require warm environments.",
  },

  // More Dogs
  {
    id: 38,
    name: "Border Collie",
    type: "dog",
    size: "medium",
    activity: "high",
    care: "difficult",
    lifespan: "12-15 years",
    weight: "30-55 lbs",
    origin: "Scotland",
    description:
      "Extremely intelligent and energetic herding dogs. They require mental stimulation and physical exercise to prevent destructive behavior.",
  },
  {
    id: 39,
    name: "Bulldog",
    type: "dog",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "8-10 years",
    weight: "40-50 lbs",
    origin: "England",
    description:
      "Known for their wrinkled face and pushed-in nose. They're gentle, calm, and make excellent family pets despite their intimidating appearance.",
  },
  {
    id: 40,
    name: "Siberian Husky",
    type: "dog",
    size: "large",
    activity: "high",
    care: "difficult",
    lifespan: "12-14 years",
    weight: "35-60 lbs",
    origin: "Siberia",
    description:
      "Working dogs bred for sledding in harsh conditions. They're energetic, independent, and require extensive exercise and mental stimulation.",
  },

  // More Cats
  {
    id: 41,
    name: "Russian Blue",
    type: "cat",
    size: "medium",
    activity: "moderate",
    care: "easy",
    lifespan: "15-20 years",
    weight: "7-12 lbs",
    origin: "Russia",
    description:
      "Known for their silvery-blue coat and green eyes. They're intelligent, loyal, and somewhat reserved with strangers.",
  },
  {
    id: 42,
    name: "Bengal Cat",
    type: "cat",
    size: "medium",
    activity: "high",
    care: "moderate",
    lifespan: "12-16 years",
    weight: "8-15 lbs",
    origin: "United States",
    description:
      "Wild-looking cats with leopard-like spots. They're active, playful, and intelligent, often enjoying water and climbing.",
  },
  {
    id: 43,
    name: "Scottish Fold",
    type: "cat",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "11-14 years",
    weight: "6-13 lbs",
    origin: "Scotland",
    description:
      "Known for their distinctive folded ears. They're calm, affectionate, and adapt well to different living situations.",
  },

  // More Birds
  {
    id: 44,
    name: "Lovebird",
    type: "bird",
    size: "small",
    activity: "high",
    care: "moderate",
    lifespan: "10-15 years",
    weight: "1.5-2.5 oz",
    origin: "Africa",
    description:
      "Small, colorful parrots known for their affectionate nature with their mates. They're social and do best in pairs.",
  },
  {
    id: 45,
    name: "Cockatoo",
    type: "bird",
    size: "large",
    activity: "high",
    care: "difficult",
    lifespan: "60-100 years",
    weight: "1-2.5 lbs",
    origin: "Australia",
    description:
      "Large parrots with distinctive crests. They're intelligent, social, and require significant attention and mental stimulation.",
  },

  // More Fish
  {
    id: 46,
    name: "Neon Tetra",
    type: "fish",
    size: "small",
    activity: "high",
    care: "easy",
    lifespan: "5-10 years",
    weight: "0.1 oz",
    origin: "South America",
    description:
      "Small, colorful schooling fish with bright blue and red stripes. They're peaceful and perfect for community aquariums.",
  },
  {
    id: 47,
    name: "Discus Fish",
    type: "fish",
    size: "medium",
    activity: "low",
    care: "difficult",
    lifespan: "10-15 years",
    weight: "2-4 oz",
    origin: "Amazon Basin",
    description:
      "Considered the king of freshwater aquarium fish. They're beautiful but require pristine water conditions and careful feeding.",
  },

  // More Reptiles
  {
    id: 48,
    name: "Blue-Tongued Skink",
    type: "reptile",
    size: "medium",
    activity: "low",
    care: "moderate",
    lifespan: "15-20 years",
    weight: "1-2 lbs",
    origin: "Australia",
    description:
      "Large lizards known for their bright blue tongues. They're docile, intelligent, and make excellent pets for reptile enthusiasts.",
  },
  {
    id: 49,
    name: "Corn Snake",
    type: "reptile",
    size: "medium",
    activity: "low",
    care: "easy",
    lifespan: "15-20 years",
    weight: "1-2 lbs",
    origin: "United States",
    description:
      "Docile, easy-to-care-for snakes that come in many color varieties. They're perfect for beginners to snake keeping.",
  },
  {
    id: 50,
    name: "Green Iguana",
    type: "reptile",
    size: "large",
    activity: "moderate",
    care: "difficult",
    lifespan: "15-20 years",
    weight: "4-17 lbs",
    origin: "Central/South America",
    description:
      "Large herbivorous lizards that require extensive care, large enclosures, and proper UV lighting. They can grow quite large and live many years.",
  },
];

// Export the data for use in other files
if (typeof module !== "undefined" && module.exports) {
  module.exports = animalsData;
}
